### ISSUE TITLE
Default mouse pointer cursor when interacting with blocks

### ISSUE THREAD

**Issue by Valer100** [ScratchAddons/ScratchAddons#6117]
### Why this would be helpful

This addon would be helpful, because some people don't like the current mouse cursor when interacting with blocks, like hovering or dragging them.

### How this addon works

My addon will make Scratch to show the deafult pointer when interacting with the blocks, instead of the pixelated hand cursor. Here is a GIF to understand how this addon works:

![demo](https://github.com/ScratchAddons/ScratchAddons/assets/122545522/ee07bd4f-cc63-4796-8556-295d1a925aaf)

**Comment by Samq64** [comment]
Usually issues are submitted before pull requests so we have time so discuss the feature.

**Comment by DNin01** [comment]
This is a pretty specific customization and I'm not sure how many users have asked for it.

Like someone else said above, it's also a good idea to keep an issue open for a reasonable amount of time before working on it so we have time to discuss it and provide feedback before the pull request is made.

Nice work, though.

**Comment by CST1229** [comment]
Personally I'm more on the opposite side and say there should be an addon to make the grabbing hand show when grabbing blocks (if any addon like this were to be added).  
That was actually intended to be the case (and is the case in things like the scratch-blocks playground), but doesn't work due to a bug (and that bug actually was fixed, but the fix was reverted due to it breaking other things).

![](https://github.com/ScratchAddons/ScratchAddons/assets/68464103/464dcbd9-7cc9-4fa0-8c61-2e441a181aff)![](https://github.com/ScratchAddons/ScratchAddons/assets/68464103/20607f33-5292-4e91-b70e-cee73f0dd7f5)

However, that's a separate issue.

**Comment by WorldLanguages** [comment]
> That was actually intended to be the case (and is the case in things like the scratch-blocks playground), but doesn't work due to a bug (and that bug actually was fixed, but the fix was reverted due to it breaking other things).

Very interesting! Can you share the links to the LLK issues/PRs?

**Comment by BroJac5246** [comment]
This is WAY too much customization for Scratch Addons.

I also prefer CST's idea, not that I support it.

And if something like this was planned for vanilla Scratch then I think it should be suggested there since the bug is fixed– this makes sense, just not for Scratch Addons.

**Comment by Valer100** [comment]
So, you don't like my addon?

**Comment by CST1229** [comment]
> Very interesting! Can you share the links to the LLK issues/PRs?

https://github.com/scratchfoundation/scratch-gui/issues/2755 https://github.com/scratchfoundation/scratch-gui/pull/5078 https://github.com/scratchfoundation/scratch-gui/pull/5096

**Comment by Secret-chest** [comment]
> This is WAY too much customization for Scratch Addons.

I disagree. It's not a radical change, but you still see it daily.

**Comment by WorldLanguages** [comment]
> This is WAY too much customization for Scratch Addons.

Unsure about that, but the addon looks useless if the user didn't change their OS cursor settings, so it's a bit hard to explain this in the addon description 🤔

**Comment by Valer100** [comment]
> the addon looks useless if the user didn't change their OS cursor settings

I don't think so. It also works even if you don't use custom mouse pointer cursors.

**Comment by WorldLanguages** [comment]
Well, the point that I think the addon may be hard to explain stands, it looks like I didn't fully understand it even with a gif.

I'm still confused though, isn't CST saying that the current behavior is a bug? The hand cursor isn't visible at all times when dragging blocks in my experience (without any addons enabled).

**Comment by Valer100** [comment]
With no addon enabled, I can still see the pixelated hand cursor when I hover a block and when I slowly drag a block. I don't know what browser are you using, but I use Firefox on Windows 11. 

The addon's main scope is to show the default mouse pointer cursor instead of the pixelated hand cursor.

**Comment by Valer100** [comment]
Also I found a post on the SA Discord server's suggestions forum about this. Here is it (it's pretty old): https://discord.com/channels/806602307750985799/1030561000807739402

**Comment by Valer100** [comment]
Also, I found a suggestion on the SA Discord server regarding the main idea of this addon. Here is the link of the suggestion: https://discord.com/channels/806602307750985799/1030561000807739402

**Comment by WorldLanguages** [comment]
cc @callumjt

**Comment by callumjt** [comment]
YES

**Comment by Valer100** [comment]
Why are you not liking this addon idea? It's just an addon like any other addon, which can be turned off if you really don't like it.

**Comment by DNin01** [comment]
> Why are you not liking this addon idea? It's just an addon like any other addon, which can be turned off if you really don't like it.

The problem is it's close to crossing the line between what customization options are and aren't worth having in Scratch Addons (an example of a customization that's a bit too much for SA: an addon that lets you customize every icon on the website, which sounds cool but is unnecessary for most users and might even be overwhelming for some). It's not that it's a bad customization option, it's just that we don't want to offer too many customizations that are unnecessary because that might hurt the user experience.

**Comment by Valer100** [comment]
Ok, now I understand.

**Comment by WorldLanguages** [comment]
> Why are you not liking this addon?

Not sure who you're referring to, but @callumjt was the one to suggest this in the Discord server but he never clarified how he came to the idea or any other details, so I was hoping he could do that now

**Comment by Valer100** [comment]
I was referring to almost everybody who talked here.
